site_name: Nil's playground
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - glightbox
nav:
  - Home:
      - Introduction: index.md
      - WhoamI: home/whoami.md
  - Home server:
      -  Asus ChromeBox 4 - Duffy: server/DuffyCbox4.md
  - Cybersecurity:
      - Application Security:
          - Introduction to Software deployment for microservices: Cybersec/AppSec/intro.md
          - Security tools for Software Deployment: Cybersec/AppSec/securitytools.md
      - Mobile Pentest: Cybersec/mobile.md

  - Bicing:
      - Intro: Bicing/Bicing.md
      - Heatmap: Bicing/Heatmap.md
      - HomeAssistant: Bicing/HomeAssistant.md
      - Bot: Bicing/Bot.md
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


